name: Deploy NeuroMul to Timeweb

on:
  push:
    branches:
      - main  # Автоматический запуск при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Обновлено до актуальной версии v4

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          mkdir -p /app/neuromul
          cd /app/neuromul
          
          if [ ! -d ".git" ]; then
            git clone https://github.com .
          else
            git pull origin main
          fi
          
          docker compose down
          docker compose up --build -d
          
          docker system prune -f
